services:
  db:
    image: postgres:18.1-bookworm
    container_name: restaurant_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dan
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: restaurantdb
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata:
